Repository nextcloud/calendar-js, pull requests merged in 2023-03, with the labels that each got.

#571 fix: tasks may return a nullish reference recurrence id
  src/components/root/abstractRecurringComponent.js
  src/components/root/toDoComponent.js
Labels: bug, 4. to release

#570 fix: adjust RRULE count when forking occurrences
  src/components/root/abstractRecurringComponent.js
  src/recurrence/recurrenceManager.js
Labels: bug, 3. to review

#579 Bump uuid from 8.3.2 to 9.0.0
  package-lock.json
  package.json
Labels: dependencies, 3. to review
