Repository nextcloud/calendar-js, pull requests merged in 2024-05, with the labels that each got.

#723 ci: Create npm-audit-fix.yml
  .github/workflows/npm-audit-fix.yml
Labels: 3. to review

#724 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#719 chore: migrate from dependabot to renovate
  .github/dependabot.yml
  renovate.json
Labels: 3. to review, techdebt
