Repository nextcloud/calendar-js, pull requests merged in 2024-09, with the labels that each got.

#751 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#760 chore(CI): Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#755 chore: update workflows from templates
  .github/workflows/lint-eslint.yml
  .github/workflows/node-test.yml
  .github/workflows/npm-audit-fix.yml
Labels: dependencies, 3. to review, automated

#761 chore: Define code owners
  .github/CODEOWNERS
Labels: 3. to review
