Repository nextcloud/calendar-js, pull requests merged in 2025-08, with the labels that each got.

#833 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#834 build: update node and npm engines versions
  package.json
Labels: dependencies

#819 ci: update npm-audit-fix.yml workflow from template
  .github/workflows/npm-audit-fix.yml
Labels: dependencies

#836 fix: time frame check of vtodos
  src/components/root/toDoComponent.js
  tests/unit/components/root/todoComponent.test.js
Labels: bug, 3. to review
